version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "feature-dependabot"

  - package-ecosystem: "npm"
    directory: "/packages/library"
    schedule:
      interval: "weekly"
    target-branch: "feature-dependabot"

  - package-ecosystem: "npm"
    directory: "/packages/docs"
    schedule:
      interval: "weekly"
    target-branch: "feature-dependabot"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "feature-dependabot"
