name: Publish Rollup Package

on:
  push:
    branches:
      - staging

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Comment out authToken line in .npmrc
        run: |
          sed -i 's|//npm.pkg.github.com/:_authToken=${GH_TOKEN}|#//npm.pkg.github.com/:_authToken=${GH_TOKEN}|' .npmrc
      - name: Comment out authToken line in packages/rollup-library .npmrc
        working-directory: packages/rollup-library
        run: |
          sed -i 's|//npm.pkg.github.com/:_authToken=${GH_TOKEN}|#//npm.pkg.github.com/:_authToken=${GH_TOKEN}|' .npmrc
      - name: Comment out authToken line in packages/rollup-swc-library .npmrc
        working-directory: packages/rollup-swc-library
        run: |
          sed -i 's|//npm.pkg.github.com/:_authToken=${GH_TOKEN}|#//npm.pkg.github.com/:_authToken=${GH_TOKEN}|' .npmrc
      - name: Comment out authToken line in packages/vite-library .npmrc
        working-directory: packages/vite-library
        run: |
          sed -i 's|//npm.pkg.github.com/:_authToken=${GH_TOKEN}|#//npm.pkg.github.com/:_authToken=${GH_TOKEN}|' .npmrc
      - name: Comment out authToken line in packages/vite-swc-library .npmrc
        working-directory: packages/vite-swc-library
        run: |
          sed -i 's|//npm.pkg.github.com/:_authToken=${GH_TOKEN}|#//npm.pkg.github.com/:_authToken=${GH_TOKEN}|' .npmrc
      - name: Comment out authToken line in apps/vite .npmrc
        working-directory: apps/vite
        run: |
          sed -i 's|//npm.pkg.github.com/:_authToken=${GH_TOKEN}|#//npm.pkg.github.com/:_authToken=${GH_TOKEN}|' .npmrc
      - name: Comment out authToken line in apps/vite-swc .npmrc
        working-directory: apps/vite-swc
        run: |
          sed -i 's|//npm.pkg.github.com/:_authToken=${GH_TOKEN}|#//npm.pkg.github.com/:_authToken=${GH_TOKEN}|' .npmrc
      - name: Comment out authToken line in apps/webpack .npmrc
        working-directory: apps/webpack
        run: |
          sed -i 's|//npm.pkg.github.com/:_authToken=${GH_TOKEN}|#//npm.pkg.github.com/:_authToken=${GH_TOKEN}|' .npmrc
      - name: Comment out authToken line in apps/webpack-swc .npmrc
        working-directory: apps/webpack-swc
        run: |
          sed -i 's|//npm.pkg.github.com/:_authToken=${GH_TOKEN}|#//npm.pkg.github.com/:_authToken=${GH_TOKEN}|' .npmrc
      - name: Authenticate with GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" >> ~/.npmrc
      - name: Installing dependencies
        run: yarn install --frozen-lockfile
      - name: Publishing the library package
        working-directory: packages/rollup-swc-library
        run: |
          yarn build:prod
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Output package details
        working-directory: packages/rollup-swc-library
        run: cat package.json
