name: Publish Package

on:
  push:
    branches: [development]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Authenticate with GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
      - name: Installing dependencies
        run: yarn install --frozen-lockfile
      - name: Navigating to the library directory
        working-directory: packages/library
        run: |
          yarn build:prod
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Output package details
        working-directory: packages/library
        run: cat package.json
