name: Tests
permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    branches:
      - dev
      - alpha
      - beta
      - rc
      - release
      - master
      - "feature-*"

env:
  PNPM_VERSION: 10.8.1
  NODE_VERSION: 22
  NX_CACHE_DIRECTORY: .nx-cache

jobs:
  dependency-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installing pnpm ${{ env.PNPM_VERSION }}
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Using Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - name: Nx cache
        uses: actions/cache@v4
        with:
          path: ${{ env.NX_CACHE_DIRECTORY }}
          key: ${{ runner.os }}-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-
            ${{ runner.os }}-nx-
      - name: Authenticating with GitHub Packages
        run: |
          # Update only the root .npmrc file since packages use symbolic links
          if [ -f ".npmrc" ]; then
            echo "Updating root .npmrc file"
            sed -i "s|//npm.pkg.github.com/:_authToken=\${GH_TOKEN}|//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}|g" .npmrc
            cat .npmrc
          else
            echo "Root .npmrc file not found, creating it"
            echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" > .npmrc
          fi
      - name: Installing dependencies
        run: pnpm install --frozen-lockfile
      - name: Running dependency audit
        run: pnpm audit
  outdated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installing pnpm ${{ env.PNPM_VERSION }}
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Using Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - name: Nx cache
        uses: actions/cache@v4
        with:
          path: ${{ env.NX_CACHE_DIRECTORY }}
          key: ${{ runner.os }}-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-
            ${{ runner.os }}-nx-
      - name: Authenticating with GitHub Packages
        run: |
          # Update only the root .npmrc file since packages use symbolic links
          if [ -f ".npmrc" ]; then
            echo "Updating root .npmrc file"
            sed -i "s|//npm.pkg.github.com/:_authToken=\${GH_TOKEN}|//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}|g" .npmrc
            cat .npmrc
          else
            echo "Root .npmrc file not found, creating it"
            echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" > .npmrc
          fi
      - name: Installing dependencies
        run: pnpm install --frozen-lockfile
      - name: Running outdated
        run: pnpm outdated
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installing pnpm ${{ env.PNPM_VERSION }}
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Using Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - name: Nx cache
        uses: actions/cache@v4
        with:
          path: ${{ env.NX_CACHE_DIRECTORY }}
          key: ${{ runner.os }}-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-
            ${{ runner.os }}-nx-
      - name: Authenticating with GitHub Packages
        run: |
          # Update only the root .npmrc file since packages use symbolic links
          if [ -f ".npmrc" ]; then
            echo "Updating root .npmrc file"
            sed -i "s|//npm.pkg.github.com/:_authToken=\${GH_TOKEN}|//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}|g" .npmrc
            cat .npmrc
          else
            echo "Root .npmrc file not found, creating it"
            echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" > .npmrc
          fi
      - name: Installing dependencies
        run: pnpm install --frozen-lockfile
      - name: Building the packages
        run: pnpm build:pkg:prod
      - name: Running lint
        run: pnpm lint
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installing pnpm ${{ env.PNPM_VERSION }}
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Using Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - name: Nx cache
        uses: actions/cache@v4
        with:
          path: ${{ env.NX_CACHE_DIRECTORY }}
          key: ${{ runner.os }}-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-
            ${{ runner.os }}-nx-
      - name: Authenticating with GitHub Packages
        run: |
          # Update only the root .npmrc file since packages use symbolic links
          if [ -f ".npmrc" ]; then
            echo "Updating root .npmrc file"
            sed -i "s|//npm.pkg.github.com/:_authToken=\${GH_TOKEN}|//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}|g" .npmrc
            cat .npmrc
          else
            echo "Root .npmrc file not found, creating it"
            echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" > .npmrc
          fi
      - name: Installing dependencies
        run: pnpm install --frozen-lockfile
      - name: Building the packages
        run: pnpm build:pkg:prod
      - name: Running unit tests
        run: pnpm test:coverage
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installing pnpm ${{ env.PNPM_VERSION }}
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Using Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - name: Nx cache
        uses: actions/cache@v4
        with:
          path: ${{ env.NX_CACHE_DIRECTORY }}
          key: ${{ runner.os }}-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-
            ${{ runner.os }}-nx-
      - name: Authenticating with GitHub Packages
        run: |
          # Update only the root .npmrc file since packages use symbolic links
          if [ -f ".npmrc" ]; then
            echo "Updating root .npmrc file"
            sed -i "s|//npm.pkg.github.com/:_authToken=\${GH_TOKEN}|//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}|g" .npmrc
            cat .npmrc
          else
            echo "Root .npmrc file not found, creating it"
            echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" > .npmrc
          fi
      - name: Installing dependencies
        run: pnpm install --frozen-lockfile
      - name: Installing Cypress binary
        run: pnpx cypress install
      - name: Installing Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
      - name: Running e2e tests
        run: pnpm e2e-run
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installing pnpm ${{ env.PNPM_VERSION }}
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Using Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - name: Nx cache
        uses: actions/cache@v4
        with:
          path: ${{ env.NX_CACHE_DIRECTORY }}
          key: ${{ runner.os }}-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-
            ${{ runner.os }}-nx-
      - name: Authenticating with GitHub Packages
        run: |
          # Update only the root .npmrc file since packages use symbolic links
          if [ -f ".npmrc" ]; then
            echo "Updating root .npmrc file"
            sed -i "s|//npm.pkg.github.com/:_authToken=\${GH_TOKEN}|//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}|g" .npmrc
            cat .npmrc
          else
            echo "Root .npmrc file not found, creating it"
            echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" > .npmrc
          fi
      - name: Installing dependencies
        run: pnpm install --frozen-lockfile
      - name: Building the project
        run: pnpm build:prod
  storybook-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installing pnpm ${{ env.PNPM_VERSION }}
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Using Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - name: Nx cache
        uses: actions/cache@v4
        with:
          path: ${{ env.NX_CACHE_DIRECTORY }}
          key: ${{ runner.os }}-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-nx-${{ hashFiles('**/pnpm-lock.yaml') }}-
            ${{ runner.os }}-nx-
      - name: Authenticating with GitHub Packages
        run: |
          # Update only the root .npmrc file since packages use symbolic links
          if [ -f ".npmrc" ]; then
            echo "Updating root .npmrc file"
            sed -i "s|//npm.pkg.github.com/:_authToken=\${GH_TOKEN}|//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}|g" .npmrc
            cat .npmrc
          else
            echo "Root .npmrc file not found, creating it"
            echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" > .npmrc
          fi
      - name: Installing dependencies
        run: pnpm install --frozen-lockfile
      - name: Building the storybook
        run: pnpm storybook:build:prod
